 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 09:42:50] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:42:50] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:43:08] "[37mGET /translationhistory HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:43:22] "[37mGET /themodels HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:45:04] "[37mGET /themodels HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:45:16] "[37mGET /themodels/devX HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:46:23] "[37mGET /themodels HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:47:10] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:47:12] "[37mGET /themodels HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:49:15] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:53:53] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:55:20] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:55:20] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:55:29] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:55:29] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:55:32] "[33mGET /modelsummary HTTP/1.1[0m" 404 -
127.0.0.1 - - [15/Oct/2020 09:55:32] "[33mGET /static/images/icons/favicon.ico HTTP/1.1[0m" 404 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 09:56:57] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:56:58] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:57:09] "[37mGET / HTTP/1.1[0m" 200 -
2020-10-15 09:57:34.484271: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-15 09:57:34.505413: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fb51abf93b0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-15 09:57:34.505449: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
127.0.0.1 - - [15/Oct/2020 09:57:35] "[32mPOST / HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2020 09:57:36] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:57:47] "[37mGET /translationhistory HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:58:00] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:58:03] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:58:42] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:58:42] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:58:59] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 09:58:59] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:35:25] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:35:25] "[36mGET /static/styles/base.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [15/Oct/2020 10:35:25] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:35:28] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 10:37:39] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/logos.py", line 5, in <module>
    app = create_app(os.getenv('FLASK_CONFIG') or 'default')
  File "/Users/davidhaase/Documents/Projects/logos/app/__init__.py", line 44, in create_app
    from .main import main as main_blueprint
  File "/Users/davidhaase/Documents/Projects/logos/app/main/__init__.py", line 28, in <module>
    from . import views, errors
File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 204
    ]
    ^
SyntaxError: invalid syntax
127.0.0.1 - - [15/Oct/2020 10:37:39] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:37:39] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:37:39] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:37:39] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:37:39] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:37:39] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:37:54] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:37:54] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:38:24] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:38:24] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:38:30] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:38:31] "[37mGET /static/styles/base.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:38:31] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:38:49] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:38:49] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 10:39:25] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:39:25] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:39:41] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:39:41] "[37mGET /static/styles/base.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:39:41] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:39:45] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:39:45] "[37mGET /static/styles/base.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:39:45] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 10:40:18] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:40:18] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:40:37] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:40:37] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:41:06] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:41:06] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:42:02] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:42:03] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:42:05] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:42:05] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:44:11] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 208, in summarize_models
    current_time=datetime.utcnow()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 65, in block "content"
    {% block page_content %}{% endblock %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 14, in block "page_content"
    <h4><a href="./modelsummary/{{ model[1] }}" target="_blank">{{ model.item() }}</a></h4>
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'item'
127.0.0.1 - - [15/Oct/2020 10:44:11] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:44:11] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:44:11] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:44:11] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:44:11] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:44:11] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:46:12] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 208, in summarize_models
    current_time=datetime.utcnow()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 65, in block "content"
    {% block page_content %}{% endblock %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 13, in block "page_content"
    {% for engine, details in all_models.item() %}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'item'
127.0.0.1 - - [15/Oct/2020 10:46:12] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:46:12] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:46:12] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:46:12] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:46:12] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:46:12] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:46:19] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 208, in summarize_models
    current_time=datetime.utcnow()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 65, in block "content"
    {% block page_content %}{% endblock %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 14, in block "page_content"
    <h4><a href="./modelsummary/{{ model[1] }}" target="_blank">{{ engine }}</a></h4>
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'model' is undefined
127.0.0.1 - - [15/Oct/2020 10:46:19] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:46:19] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:46:19] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:46:20] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:46:20] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:46:20] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:46:44] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 208, in summarize_models
    current_time=datetime.utcnow()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 65, in block "content"
    {% block page_content %}{% endblock %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 14, in block "page_content"
    <h4><a href="./modelsummary/{{ model[1] }}" target="_blank">{{ engine }}</a></h4>
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'model' is undefined
127.0.0.1 - - [15/Oct/2020 10:46:44] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:46:44] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:46:44] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:46:44] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:46:44] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:46:44] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:47:17] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 208, in summarize_models
    current_time=datetime.utcnow()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 65, in block "content"
    {% block page_content %}{% endblock %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 25, in block "page_content"
    <td>{{ model[2] }}</td>
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'model' is undefined
127.0.0.1 - - [15/Oct/2020 10:47:17] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:47:17] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:47:17] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:47:17] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:47:17] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:47:17] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:47:54] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:47:54] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 10:51:40] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:51:41] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 10:52:05] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 10:52:06] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 11:04:30] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/logos.py", line 5, in <module>
    app = create_app(os.getenv('FLASK_CONFIG') or 'default')
  File "/Users/davidhaase/Documents/Projects/logos/app/__init__.py", line 44, in create_app
    from .main import main as main_blueprint
  File "/Users/davidhaase/Documents/Projects/logos/app/main/__init__.py", line 28, in <module>
    from . import views, errors
File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 198
    languages = f'{model['source_lang_en']} -> {model['target_lang_en']}'
                                       ^
SyntaxError: invalid syntax
127.0.0.1 - - [15/Oct/2020 11:04:30] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:04:30] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:04:30] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:04:30] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:04:30] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:04:30] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:05:19] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:05:19] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 11:08:23] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 201, in summarize_models
    all_models[model['build_display_name']].append(languages, training_vars, date)
TypeError: append() takes exactly one argument (3 given)
127.0.0.1 - - [15/Oct/2020 11:08:23] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:08:23] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:08:23] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:08:23] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:08:23] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:08:23] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 11:08:56] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:08:57] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 11:12:22] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:12:22] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 11:16:29] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:16:29] "[37mGET /static/styles/base.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:16:30] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:17:26] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:17:26] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:18:19] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:18:19] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 11:21:52] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 204, in summarize_models
    bleus += f'{score}: {model["BLEUs"]["score"]}, '
KeyError: 'score'
127.0.0.1 - - [15/Oct/2020 11:21:52] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:21:52] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:21:52] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:21:52] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:21:53] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:21:53] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 11:23:07] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 204, in summarize_models
    bleus += score + ': ' + model['BLEUs']['score'] + ', '
KeyError: 'score'
127.0.0.1 - - [15/Oct/2020 11:23:07] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:23:07] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:23:07] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:23:07] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:23:07] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:23:07] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 11:23:30] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:23:30] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 11:24:30] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:24:30] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 11:24:49] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:24:49] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 11:28:06] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 225, in summarize_models
    current_time=datetime.utcnow()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 65, in block "content"
    {% block page_content %}{% endblock %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 28, in block "page_content"
    {% for score in details[4] %}
TypeError: 'datetime.datetime' object is not iterable
127.0.0.1 - - [15/Oct/2020 11:28:06] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:28:06] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:28:06] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:28:06] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:28:06] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:28:07] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:28:45] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:28:45] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:29:50] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:29:50] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:34:15] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:34:15] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:34:51] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:34:51] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:38:24] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:38:24] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:38:38] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:38:39] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 11:46:14] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:46:15] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:46:38] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:46:38] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:47:07] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:47:07] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:49:19] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:49:19] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 11:54:42] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:54:42] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:55:57] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:55:57] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:56:06] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:56:07] "[37mGET /static/styles/base.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:56:07] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:56:39] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:56:39] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:57:34] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 221, in summarize_models
    current_time=datetime.utcnow()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 65, in block "content"
    {% block page_content %}{% endblock %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 30, in block "page_content"
    {% for label, score in details[2].items() %}
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'items'
127.0.0.1 - - [15/Oct/2020 11:57:34] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:57:34] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:57:34] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:57:34] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:57:34] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:57:34] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 11:59:20] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 223, in summarize_models
    current_time=datetime.utcnow()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 65, in block "content"
    {% block page_content %}{% endblock %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 30, in block "page_content"
    {% for label, score in details[2].items() %}
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'items'
127.0.0.1 - - [15/Oct/2020 11:59:20] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:59:20] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:59:20] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:59:20] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:59:20] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:59:20] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 11:59:39] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 223, in summarize_models
    current_time=datetime.utcnow()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 65, in block "content"
    {% block page_content %}{% endblock %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 30, in block "page_content"
    {% for label, score in details[2].items() %}
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'items'
127.0.0.1 - - [15/Oct/2020 11:59:39] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:59:39] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:59:39] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:59:39] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:59:39] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 11:59:39] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:00:13] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:00:14] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:00:20] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 223, in summarize_models
    current_time=datetime.utcnow()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 65, in block "content"
    {% block page_content %}{% endblock %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 30, in block "page_content"
    {% for label, score in details[3].items() %}
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'items'
127.0.0.1 - - [15/Oct/2020 12:00:20] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:00:20] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:00:20] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:00:20] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:00:20] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:00:20] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 12:01:22] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 221, in summarize_models
    current_time=datetime.utcnow()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 65, in block "content"
    {% block page_content %}{% endblock %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 30, in block "page_content"
    {% for label, score in details[2].items() %}
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'items'
127.0.0.1 - - [15/Oct/2020 12:01:22] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:01:22] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:01:22] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:01:22] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:01:22] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:01:22] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 12:01:47] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 221, in summarize_models
    current_time=datetime.utcnow()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 65, in block "content"
    {% block page_content %}{% endblock %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 30, in block "page_content"
    {% for label, score in details[2].items() %}
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'items'
127.0.0.1 - - [15/Oct/2020 12:01:47] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:01:47] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:01:47] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:01:47] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:01:47] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:01:47] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:02:16] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 221, in summarize_models
    current_time=datetime.utcnow()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 65, in block "content"
    {% block page_content %}{% endblock %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 30, in block "page_content"
    <!-- {% for label, score in details[2].items() %}       -->
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'items'
127.0.0.1 - - [15/Oct/2020 12:02:16] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:02:16] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:02:16] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:02:16] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:02:16] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:02:16] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:02:28] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 221, in summarize_models
    current_time=datetime.utcnow()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 65, in block "content"
    {% block page_content %}{% endblock %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 30, in block "page_content"
    <!-- {% for label, score in details[2].items() %}       -->
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'items'
127.0.0.1 - - [15/Oct/2020 12:02:28] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:02:28] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:02:28] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:02:28] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:02:28] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:02:28] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:02:30] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 221, in summarize_models
    current_time=datetime.utcnow()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 2, in top-level template code
    {% import "bootstrap/wtf.html" as wtf %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/base.html", line 65, in block "content"
    {% block page_content %}{% endblock %}
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 30, in block "page_content"
    <!-- {% for label, score in details[2].items() %}       -->
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'items'
127.0.0.1 - - [15/Oct/2020 12:02:30] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:02:30] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:02:30] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:02:30] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:02:30] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:02:30] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:02:40] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:02:40] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:03:58] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:03:58] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:04:51] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:04:51] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 12:07:38] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:07:38] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:08:59] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:08:59] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 12:17:09] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:17:09] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 12:20:28] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/logos.py", line 5, in <module>
    app = create_app(os.getenv('FLASK_CONFIG') or 'default')
  File "/Users/davidhaase/Documents/Projects/logos/app/__init__.py", line 44, in create_app
    from .main import main as main_blueprint
  File "/Users/davidhaase/Documents/Projects/logos/app/main/__init__.py", line 28, in <module>
    from . import views, errors
File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 197
    training_params = f'{model['subset']}K {model['epochs']}e'
                                     ^
SyntaxError: invalid syntax
127.0.0.1 - - [15/Oct/2020 12:20:28] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:20:28] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:20:28] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:20:28] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:20:28] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:20:28] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:20:51] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:20:51] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:21:55] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:21:55] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:22:23] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:22:23] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 12:22:55] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:22:55] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 12:27:14] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/logos.py", line 5, in <module>
    app = create_app(os.getenv('FLASK_CONFIG') or 'default')
  File "/Users/davidhaase/Documents/Projects/logos/app/__init__.py", line 44, in create_app
    from .main import main as main_blueprint
  File "/Users/davidhaase/Documents/Projects/logos/app/main/__init__.py", line 28, in <module>
    from . import views, errors
File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 209
    all_models[model['build_display_name']]['details'] details
                                                             ^
SyntaxError: invalid syntax
127.0.0.1 - - [15/Oct/2020 12:27:14] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:27:14] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:27:14] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:27:14] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:27:14] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:27:14] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:27:31] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:27:31] "[37mGET /static/styles/base.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:27:31] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 12:30:02] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 225, in summarize_models
    current_time=datetime.utcnow()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/davidhaase/Documents/Projects/logos/app/templates/modelsummary.html", line 26, in template
    {% endfor % }
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got '%'
127.0.0.1 - - [15/Oct/2020 12:30:02] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:30:02] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:30:02] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:30:02] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:30:02] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:30:02] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:30:22] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:30:22] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:30:54] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:30:54] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:31:42] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:31:42] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:33:08] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:33:08] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:34:30] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:34:30] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:35:01] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:35:01] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:35:22] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:35:22] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:37:26] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:37:26] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:38:02] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:38:02] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:38:14] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:38:14] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:38:18] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:38:18] "[37mGET /static/styles/base.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:38:18] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 12:43:27] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/logos.py", line 5, in <module>
    app = create_app(os.getenv('FLASK_CONFIG') or 'default')
  File "/Users/davidhaase/Documents/Projects/logos/app/__init__.py", line 44, in create_app
    from .main import main as main_blueprint
  File "/Users/davidhaase/Documents/Projects/logos/app/main/__init__.py", line 28, in <module>
    from . import views, errors
File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 208
    details[languages] = {'bleus':bleus, 'date_created', date_created}
                                                       ^
SyntaxError: invalid syntax
127.0.0.1 - - [15/Oct/2020 12:43:27] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:43:27] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:43:27] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:43:27] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:43:27] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:43:27] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:43:50] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 208, in summarize_models
    details[languages] = {'bleus':bleus, 'date_created' : date_created}
NameError: name 'details' is not defined
127.0.0.1 - - [15/Oct/2020 12:43:50] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:43:50] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:43:50] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:43:50] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:43:51] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:43:51] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 12:44:07] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:44:07] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 12:45:50] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 207, in summarize_models
    if languages not in details:
NameError: name 'details' is not defined
127.0.0.1 - - [15/Oct/2020 12:45:50] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:45:50] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:45:50] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:45:50] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:45:50] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:45:50] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 12:46:51] "[35m[1mGET /modelsummary HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/logos.py", line 5, in <module>
    app = create_app(os.getenv('FLASK_CONFIG') or 'default')
  File "/Users/davidhaase/Documents/Projects/logos/app/__init__.py", line 44, in create_app
    from .main import main as main_blueprint
  File "/Users/davidhaase/Documents/Projects/logos/app/main/__init__.py", line 28, in <module>
    from . import views, errors
File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 201
    'details' : {}
            ^
SyntaxError: invalid syntax
127.0.0.1 - - [15/Oct/2020 12:46:51] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:46:51] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:46:51] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:46:52] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:46:52] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:46:52] "[37mGET /modelsummary?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:47:10] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:47:11] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:48:35] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:48:35] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:49:45] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:49:46] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:53:54] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:53:54] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:58:59] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 12:58:59] "[33mGET /Users/davidhaase/Documents/Learn/Flatiron/Projects/machine-translator/models/es_to_en/basic_75K_35E_fixed/images/accuracy.png HTTP/1.1[0m" 404 -
127.0.0.1 - - [15/Oct/2020 12:58:59] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 13:43:02] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 13:43:02] "[33mGET /static/accuracy.png HTTP/1.1[0m" 404 -
127.0.0.1 - - [15/Oct/2020 13:43:02] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 13:43:36] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 13:43:37] "[33mGET /static/imagles/accuracy.png HTTP/1.1[0m" 404 -
127.0.0.1 - - [15/Oct/2020 13:43:37] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 13:43:55] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 13:43:55] "[37mGET /static/images/accuracy.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 13:43:55] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 13:48:19] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 13:48:20] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 13:52:19] "[33mGET /modelsummary/devX HTTP/1.1[0m" 404 -
127.0.0.1 - - [15/Oct/2020 13:52:19] "[33mGET /static/images/icons/favicon.ico HTTP/1.1[0m" 404 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 13:52:54] "[37mGET /modelsummary/devX HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 13:52:54] "[33mGET /modelsummary/url_for('static',%20filename='images/accuracy.png') HTTP/1.1[0m" 404 -
127.0.0.1 - - [15/Oct/2020 13:52:54] "[33mGET /modelsummary/url_for('static',%20filename='images/loss.png') HTTP/1.1[0m" 404 -
127.0.0.1 - - [15/Oct/2020 13:52:54] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 13:55:26] "[37mGET /modelsummary/devX HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 13:55:26] "[33mGET /modelsummary/url_for('static',%20filename='images/accuracy.png') HTTP/1.1[0m" 404 -
127.0.0.1 - - [15/Oct/2020 13:55:26] "[33mGET /modelsummary/url_for('static',%20filename='images/loss.png') HTTP/1.1[0m" 404 -
127.0.0.1 - - [15/Oct/2020 13:55:26] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
 * Detected change in '/Users/davidhaase/Documents/Projects/logos/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 318-090-404
127.0.0.1 - - [15/Oct/2020 13:59:09] "[35m[1mGET /modelsummary/devX HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/Users/davidhaase/Documents/Projects/logos/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/davidhaase/Documents/Projects/logos/logos.py", line 5, in <module>
    app = create_app(os.getenv('FLASK_CONFIG') or 'default')
  File "/Users/davidhaase/Documents/Projects/logos/app/__init__.py", line 44, in create_app
    from .main import main as main_blueprint
  File "/Users/davidhaase/Documents/Projects/logos/app/main/__init__.py", line 28, in <module>
    from . import views, errors
File "/Users/davidhaase/Documents/Projects/logos/app/main/views.py", line 379
    accuracy_path = url_for('static', filename=images/accuracy.png')
                                                                   ^
SyntaxError: EOL while scanning string literal
127.0.0.1 - - [15/Oct/2020 13:59:09] "[37mGET /modelsummary/devX?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 13:59:09] "[37mGET /modelsummary/devX?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 13:59:09] "[37mGET /modelsummary/devX?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 13:59:09] "[37mGET /modelsummary/devX?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 13:59:09] "[37mGET /modelsummary/devX?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 13:59:09] "[37mGET /modelsummary/devX?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 13:59:44] "[37mGET /modelsummary/devX HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 13:59:44] "[37mGET /static/images/loss.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 13:59:44] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:01:03] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:02:11] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:02:13] "[37mGET /modelsummary/devX HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:03:21] "[37mGET /modelsummary/devX HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:03:21] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:04:08] "[37mGET /modelsummary/devX HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:04:08] "[37mGET /static/styles/base.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:04:08] "[37mGET /static/images/loss.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:04:08] "[37mGET /static/images/accuracy.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:04:08] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:06:48] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:06:50] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:06:52] "[37mGET /modelsummary/devX HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:07:35] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:07:35] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:08:11] "[37mGET /modelsummary/devX HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:10:01] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:10:04] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:10:05] "[37mGET /modelsummary/devX HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:10:53] "[37mPOST / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:11:15] "[37mGET / HTTP/1.1[0m" 200 -
2020-10-15 14:11:21.443735: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-15 14:11:21.469393: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7ff32bd9c6b0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-15 14:11:21.469437: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
127.0.0.1 - - [15/Oct/2020 14:11:22] "[32mPOST / HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2020 14:11:23] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:11:23] "[32mPOST / HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2020 14:11:23] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:11:36] "[32mPOST / HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2020 14:11:36] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:11:51] "[32mPOST / HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2020 14:11:51] "[32mPOST / HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2020 14:11:52] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:12:03] "[32mPOST / HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2020 14:12:03] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:12:14] "[32mPOST / HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2020 14:12:15] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:12:22] "[37mGET /translationhistory HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:12:46] "[32mPOST / HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2020 14:12:47] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:13:02] "[32mPOST / HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2020 14:13:03] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:13:07] "[37mGET /translationhistory HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:13:17] "[33mGET /themodels HTTP/1.1[0m" 404 -
127.0.0.1 - - [15/Oct/2020 14:13:18] "[33mGET /static/images/icons/favicon.ico HTTP/1.1[0m" 404 -
127.0.0.1 - - [15/Oct/2020 14:14:02] "[37mGET /translationhistory HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:14:04] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:16:09] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:16:09] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:17:10] "[37mGET /modelsummary/devX HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:17:46] "[37mGET /modelsummary/devX HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:17:46] "[37mGET /static/styles/base.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:17:46] "[37mGET /static/images/accuracy.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:17:46] "[37mGET /static/images/loss.png HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:17:46] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:19:25] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:19:38] "[32mPOST / HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2020 14:19:38] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:19:49] "[32mPOST / HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2020 14:19:49] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:20:02] "[32mPOST / HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2020 14:20:02] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:20:16] "[32mPOST / HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2020 14:20:16] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:20:20] "[37mGET /translationhistory HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:20:23] "[37mGET /translationhistory?page=2 HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:20:28] "[37mGET /modelsummary HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:21:29] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:21:34] "[37mGET /translationhistory HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:21:40] "[37mGET /translationhistory?page=2 HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:21:45] "[37mGET /translationhistory HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:21:48] "[37mGET /identify HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:21:49] "[37mGET /diagnose HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:21:50] "[37mGET /about HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:21:51] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:22:11] "[32mPOST / HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2020 14:22:11] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:22:35] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:22:35] "[37mGET /static/styles/base.css HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:22:35] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:22:45] "[37mGET /translationhistory HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:22:49] "[37mGET /translationhistory?page=2 HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:22:51] "[37mGET /translationhistory HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:22:59] "[37mGET /translationhistory?page=2 HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:23:01] "[37mGET /translationhistory HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:23:06] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:23:13] "[32mPOST / HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2020 14:23:13] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:23:20] "[37mGET /translationhistory HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:23:35] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:23:41] "[32mPOST / HTTP/1.1[0m" 302 -
127.0.0.1 - - [15/Oct/2020 14:23:42] "[37mGET / HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:23:49] "[37mGET /translationhistory HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:25:21] "[37mGET /translationhistory HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:25:24] "[37mGET /diagnose HTTP/1.1[0m" 200 -
127.0.0.1 - - [15/Oct/2020 14:25:25] "[37mGET /about HTTP/1.1[0m" 200 -
